### ISSUE TITLE
DeviceNotifyHook should not need Windows Forms control

### ISSUE THREAD

**Issue by andrasfuchs** [madwizard-thomas/winusbnet#17] opened 2017-03-13 08:12 UTC
I tried to use the attachment and detachment events in a console application, but I was unable to do so. I'm not sure if I missed something, but I found only the USBNotifier class, which needs a Windows Forms control as a parameter in its constructor. Is there any other way to accomplish device attachment/removal detection?

**Comment by madwizard-thomas** [comment] 2017-03-13 18:55
Duplicate of #11

**Closed by madwizard-thomas** 2017-03-13 18:55 UTC
