### ISSUE TITLE
Using WinUSB.sys as function driver, Digital  Signature on Cat file is not being recognized..

### ISSUE THREAD

**Issue by ameshlal** [madwizard-thomas/winusbnet#23] opened 2018-02-27 15:18 UTC
I am using WinUSB as a function driver in one of our project (little old). The following is the folder structure.

driver
|--drivername.inf
|--drivername.cat
|--amd64
------       |--WdfCoInstaller01005.dll
------       |--Winusbcoinstaller.dll
|--i386
------       |--WdfCoInstaller01005.dll
------       |--Winusbcoinstaller.dll

The INF file looks like this.

`[Version]
Signature = "$Windows NT$"
Class =makdevice
ClassGuid={ad769fbf-c592-4b8c-940a-6e3782a545e8}
Provider = %ProviderName%
DriverVer=02/27/2018,6.00.2064
CatalogFile=%MFGFILENAME%.cat

; ========== Manufacturer/Models sections ===========

[Manufacturer]
%ProviderName% = makInc,NTx86,NTamd64

[makInc.NTx86]
%USB\MyDevice.DeviceDesc% =USB_Install, USB\VID_1448&PID_4AC0&REV_0001

[makInc.NTamd64]
%USB\MyDevice.DeviceDesc% =USB_Install, USB\VID_1448&PID_4AC0&REV_0001

; =================== Installation ===================

[ClassInstall32]
AddReg=SampleClass_RegistryAdd

[SampleClass_RegistryAdd]
HKR,,,,%ClassName%

;[1]
[USB_Install]
Include=winusb.inf
Needs=WINUSB.NT

;[2]
[USB_Install.Services]
Include=winusb.inf
AddService=WinUSB,0x00000002,WinUSB_ServiceInstall

;[3]
[WinUSB_ServiceInstall]
DisplayName     = %WinUSB_SvcDesc%
ServiceType     = 1
StartType       = 3
ErrorControl    = 1
ServiceBinary   = %12%\WinUSB.sys

;[4]
[USB_Install.Wdf]
KmdfService=WINUSB, WinUsb_Install

[WinUSB_Install]
KmdfLibraryVersion=1.5

;[5]
[USB_Install.HW]
AddReg=Dev_AddReg

[Dev_AddReg]
HKR,,DeviceInterfaceGUIDs,0x10000,"{55630179-b622-4834-8ff7-9916b1446884}"

;[6]
[USB_Install.CoInstallers]
AddReg=CoInstallers_AddReg
CopyFiles=CoInstallers_CopyFiles

[CoInstallers_AddReg]
HKR,,CoInstallers32,0x00010000,"WdfCoInstaller01005.dll,WdfCoInstaller","WinUSBCoInstaller.dll"

[CoInstallers_CopyFiles]
WinUSBCoInstaller.dll
WdfCoInstaller01005.dll

[DestinationDirs]
CoInstallers_CopyFiles=11

; ================= Source Media Section =====================
;[7]

[SourceDisksNames]
1 = %DISK_NAME%,,,\i386
2 = %DISK_NAME%,,,\amd64

[SourceDisksFiles.x86]
WinUSBCoInstaller.dll=1
WdfCoInstaller01005.dll=1

[SourceDisksFiles.NTamd64]
WinUSBCoInstaller.dll=2
WdfCoInstaller01005.dll=2

; =================== Strings ===================

[Strings]
MFGFILENAME="mak"
ProviderName="mak Inc"
ClassName="mak device"
USB\MyDevice.DeviceDesc="mak"
WinUSB_SvcDesc="mak"
DISK_NAME="Drivers"
`

I have generated the mak.cat file using Inf2Cat utility, then digitally signed using a Digicert EV Code signing certificate. And using these files an Installshield   setup has been generated for the driver. But while installing the driver, the digital signature of the driver is not being recognized. 
And the following error is being shown. 
**windows can't verify the publisher of this driver software**

<img src='https://i.imgur.com/ZISpCIv.jpg' />

The digital  signature of the .cat file seems valid. (I can right click the file and see the same in the properties)
The following is the DIFX options provided in _install-shield_ to generate the driver installer.

<img src='https://i.imgur.com/FToBYK4.jpg' />

Please help.. I have tried lot of forums.. Could not find any solution so far.. Please guide..

**Comment by madwizard-thomas** [comment] 2018-03-07 20:00
I'm not sure what the problem is, it's been a long time since I created an .inf package and the signing rules have changed with every windows version. The inf i used in the past can be found in the wiki. Maybe ask your certificate's vendor for help?

Closing this issue since it is not related to this library.

**Closed by madwizard-thomas** 2018-03-07 20:00 UTC
